Database with PullConnection
ancherm/ErmakovJava pull request #4
Opened 2024-01-29 19:23 UTC by ancherm

2024-01-30 18:03 UTC, aleksandr-chermashentsev requested changes
НЕ УДАЛЯЙ PR! Просто пушни в ветку 6.1-dev, изменения подхватятся.

2024-01-30 18:03 UTC, aleksandr-chermashentsev commented on src/ru/chermashentsev/database/Connection.java
>  public class Connection {
Т.к. Connection не виден пользователю, его можно сделать package-private. То же самое для Database. Входной точкой в пакет можно сделать статический метод ConnectionPool.create(), который будет возвращать ConnectionPool с преднастроенной Database и всеми Connection'ами.

2024-02-06 23:01 UTC, ancherm commented on src/ru/chermashentsev/database/Connection.java
>      public void setConnection(Database database) {
Это всё еще не понял

2024-02-06 23:02 UTC, ancherm commented on src/ru/chermashentsev/database/ConnectionPool.java
> +    private final List<ConnectionProxy> connectionList;
По итогу, использовал стек, потому что, как по мне, в этой задаче с ним проще работать

2024-02-07 10:12 UTC, aleksandr-chermashentsev requested changes

2024-02-07 10:12 UTC, aleksandr-chermashentsev commented on src/ru/chermashentsev/database/ConnectionPool.java
> +    void disconnect(ConnectionProxy connection) {
```suggestion
    void disconnect(Connection connection) {
```

2024-02-07 10:12 UTC, aleksandr-chermashentsev commented on src/ru/chermashentsev/database/ConnectionProxy.java
> +        connectionPool.disconnect(this);
Перед disconnect проверь что приконнекчен. Передавай в disconnect ссылку на connection, а не ConnectionProxy

2024-02-08 09:54 UTC, aleksandr-chermashentsev approved these changes

2024-02-10 21:57 UTC, closed without merging